### ISSUE TITLE
Store因ngOnDestory调用而被注销，导致再次操作时报错。

### ISSUE THREAD

**Issue by 791045873** [worktile/store#68]
该问题是我在单元测试时发现的。
测试代码如下

````
import { TestBed } from "@angular/core/testing"
import { of, skip, take } from "rxjs"
import { UpdateWaterProjectVm } from "../open-api/models"
import { WaterProjectService } from "../open-api/services"
import { ProjectStore } from "./project.store"
import { TestScheduler } from 'rxjs/testing';

const projectList = [
  {iCode: '1', name: '1', coord: [1,1]},
  {iCode: '2', name: '2', coord: [1,1]},
]

describe('测试projectStore中对project的操作', () => {
  let projectStore: ProjectStore
  let testScheduler: TestScheduler
  beforeAll(() => {
    TestBed.configureTestingModule({
      providers: [ProjectStore, {
        provide: WaterProjectService,
        useValue: {
          waterProjects: () => of(projectList),
          update: () => of({iCode: '2', type: 'someTypeNotUndefined', name:'updated', coord: [1,1]})
        }
      }]
    })
    projectStore = TestBed.inject(ProjectStore)
  })

  beforeEach(() => {
    testScheduler = new TestScheduler((actual, expected) => {
      expect(actual).toEqual(expected);
    });
  })

 //   测试一 
  it('获取project数据后可以正确存储', (done) => {
    projectStore.entities$.pipe(skip(1), take(1)).subscribe(list => {
      expect(list).toEqual(expect.arrayContaining([
        expect.objectContaining({iCode: '1', name: '1', coord: [1,1]}),
        expect.objectContaining({iCode: '2', name: '2', coord: [1,1]}),
      ]))
      done()
    })

    projectStore.fetchProjectList({
      regionICode: 'regionICode',
      rlICode: 'rlICode'
    })
  })

  //   rxjs测试
  it('用户确认后更新project详情', () => {
    const progress = projectStore.canUpdateProject({ iCode: '2', type: 'someTypeNotUndefined', name:'updated' } as UpdateWaterProjectVm, () => {
      return of(true)
    })
    testScheduler.run(helpers => {
      const { expectObservable } = helpers
      expectObservable(progress).toBe('(a|)', { a: {iCode: '2', type: 'someTypeNotUndefined', name:'updated', coord: [1,1]} })
    })
  })
})
````

如上所示，如果既运行测试一，又运行rxjs测试会有如下流程（我在store的源码里加入了console.log）

````
console.log
    register StoreInstanceId ProjectStore

      at StoreFactory.register (node_modules/@tethys/store/fesm2020/tethys-store.mjs:294:17)

  console.log
    store dispatch storeInstance存在

      at InternalDispatcher.dispatch (node_modules/@tethys/store/fesm2020/tethys-store.mjs:442:17)

  console.log
    store destory unregister

      at ProjectStore.ngOnDestroy (node_modules/@tethys/store/fesm2020/tethys-store.mjs:688:17)

  console.log
    unregister StoreInstanceId ProjectStore

      at StoreFactory.unregister (node_modules/@tethys/store/fesm2020/tethys-store.mjs:299:17)

  console.log
    store dispatch undefined

      at InternalDispatcher.dispatch (node_modules/@tethys/store/fesm2020/tethys-store.mjs:442:17)
````

可以看到他在第一次dispatch之后调用了unregister，从而导致第二次dispatch时报错
通过查看源码，我发现unregister是在store的ngDestory生命周期里被触发的。
但是，我的projectStore是放在在TestBed.configureTestingModule上的，为什么会被销毁呢？

并且，如果不执行测试一，直接执行rxjs测试，不会报错。代码执行流程如下：
````
console.log
    register StoreInstanceId ProjectStore

      at StoreFactory.register (node_modules/@tethys/store/fesm2020/tethys-store.mjs:294:17)

  console.log
    store dispatch storeInstance存在

      at InternalDispatcher.dispatch (node_modules/@tethys/store/fesm2020/tethys-store.mjs:442:17)

  console.log
    store dispatch storeInstance存在

      at InternalDispatcher.dispatch (node_modules/@tethys/store/fesm2020/tethys-store.mjs:442:17)

  console.log
    store destory unregister

      at ProjectStore.ngOnDestroy (node_modules/@tethys/store/fesm2020/tethys-store.mjs:688:17)

  console.log
    unregister StoreInstanceId ProjectStore

      at StoreFactory.unregister (node_modules/@tethys/store/fesm2020/tethys-store.mjs:299:17)
````

希望能得到帮助，谢谢

**Comment by why520crazy** [comment]
@791045873 这是因为 Angular 在新版的测试中默认 `destroyAfterEach` 开启了，所以每个测试用例执行结束都调用了服务的 ngOnDestroy，解决这个问题有两个方案
1. 手动在 configureTestingModule 中设置 `destroyAfterEach` 为 false，在 afterAll 后手动调用  projectStore.ngOnDestroy();

```ts
 let projectStore: ProjectStore;
    beforeAll(() => {
        TestBed.configureTestingModule({
            providers: [ProjectStore],
            teardown: {
                destroyAfterEach: false
            }
        });
        projectStore = TestBed.inject(ProjectStore);
    });

    afterAll(() => {
        projectStore.ngOnDestroy();
    });
```

2. 把 configureTestingModule 从 `beforeAll` 移动到 `beforeEach`

**Comment by 791045873** [comment]
谢谢
